# -*- coding: utf-8 -*-
"""App.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q_i5SwWMNv_iPTRqgoeT8rzICBoU18vy
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib

# Load model
model = joblib.load("model_xgb.pkl")

st.title("📱 Prediksi Tingkat Depresi Ponsel Remaja")

# Input fitur
st.subheader("Masukkan data remaja:")
gender = st.selectbox("Jenis Kelamin", ["Male", "Female", "Other"])
school_grade = st.selectbox("Tingkat Sekolah", ["SMP", "SMA", "Kuliah"])
daily_usage_hours = st.slider("Jam penggunaan ponsel per hari", 0.0, 24.0, 5.0)
phone_checks = st.slider("Jumlah cek ponsel per hari", 0, 100, 30)
time_social = st.slider("Waktu untuk media sosial (jam)", 0.0, 10.0, 2.0)
time_gaming = st.slider("Waktu untuk game (jam)", 0.0, 10.0, 1.0)
time_edu = st.slider("Waktu untuk edukasi (jam)", 0.0, 10.0, 1.5)
purpose = st.selectbox("Tujuan utama penggunaan", ["Communication", "Entertainment", "Education", "Other"])

# Encoding
gender_map = {"Female": 0, "Male": 1, "Other": 2}
grade_map = {"SMP": 0, "SMA": 1, "Kuliah": 2}

input_df = pd.DataFrame([{
    "Gender": gender_map[gender],
    "School_Grade": grade_map[school_grade],
    "Daily_Usage_Hours": daily_usage_hours,
    "Phone_Checks_Per_Day": phone_checks,
    "Time_on_Social_Media": time_social,
    "Time_on_Gaming": time_gaming,
    "Time_on_Education": time_edu,
    "Phone_Usage_Purpose_Education": int(purpose == "Education"),
    "Phone_Usage_Purpose_Entertainment": int(purpose == "Entertainment"),
    "Phone_Usage_Purpose_Other": int(purpose == "Other"),
    "Total_App_Time": time_social + time_gaming + time_edu,
    "Phone_Checks_Per_Hour": phone_checks / (daily_usage_hours + 0.1)
}])

# Prediksi
if st.button("Prediksi"):
    prediction = model.predict(input_df)[0]
    st.success(f"📊 Tingkat kecanduan diprediksi: **{prediction:.2f}**")